version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/Scripts/activate
            pip install pytest selenium
      - run:
          name: Run tests
          command: |
            . venv/Scripts/activate
            pytest

workflows:
  version: 2
  test:
    jobs:
      - test
 
